#!/usr/bin/env python3
"""Every number the documents assert, checked against the evidence that produced it.

A judge should not have to take a figure on trust, and neither should we. This reads
`room.json`, the git history and the committed harness report, extracts what each one
actually says, and then looks for that in `README.md` and `FACTORY.md`. A figure the
evidence does not produce is printed back with the document, the line and what the
evidence says instead.

    python3 verify_claims.py            # exit 0 only when every claim holds
    python3 verify_claims.py --list     # print the claims and the evidence, check nothing

Standard library only, and CI runs it, so a number cannot drift away from the evidence
without the build going red.

Matching is deliberately narrow. A bare number is not enough: `README.md` once claimed
"highest contiguous stage: 3" while the evidence said 4, and a checker that accepted any
line containing a `4` would have passed it, because line 14 of the same file reads
"stage-1/ through stage-4/". So a claim either names the context the figure has to
appear in (`near`), or counts the lines it is supposed to produce (`rows`).

`docs/EVIDENCE.md` is the human-readable half of this, and it is generated by
`--markdown`, so the two cannot disagree either.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
ROOM = ROOT / "room.json"
RUNS = ROOT / "docs" / "harness-runs"
DOCS = ("README.md", "FACTORY.md")

# Sentences a seat is forbidden to post outright, from the message discipline section in
# every mandate. Zero of these in the room is the measurable half of "silence is the
# default"; the other half is that every text message carries something.
FILLER = re.compile(
    r"^(standing by|noted|acknowledged|quiet|no action|holding|waiting|silence)\b", re.I)
TOKEN_USAGE = re.compile(r"Token usage: input=(\d+) output=(\d+)")
VERDICT = re.compile(r"^(?:@\S+\s+)*(ACCEPT|REJECT)\b")

# The revision each stage was locked at, as FACTORY.md records it. A revision that is not
# in the git history is a stage lock that never happened.
STAGE_LOCKS = {"1": "35e2fa1", "2": "bea1c8a", "3": "92d9a5f", "4": "b88cb7b"}

STAGE_ROW = r"^\|\s*`stage-(\d)/`\s*\|"


def _role(name: str) -> str:
    """`factory-architect-df` -> `architect`. The `-df` suffix every seat shares would
    make all three read the same, and `factory-` says nothing."""
    return name.split("-")[-2] if name.count("-") > 1 else name


def _word(n: int) -> str:
    """`7` -> `seven`. Documents write small counts out, and a checker that only accepts
    digits fails a document for being well written."""
    words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
             7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}
    return words.get(n, str(n))


def _locks_mentioned(data: dict) -> int:
    """How many distinct revisions the room announces as locked.

    A stage lock is the coordinator committing a revision as that stage's answer, so it is
    counted as distinct short hashes said in the same message as the word "lock". More
    than the number of stages is expected: a stage can be re-locked after a defect.
    """
    locks: set[str] = set()
    for m in data.get("messages") or []:
        if m.get("messageType") != "text":
            continue
        content = str(m.get("content", ""))
        if re.search(r"\block", content, re.I):
            locks.update(re.findall(r"\b[0-9a-f]{7}\b", content))
    return len(locks)


# --- evidence ---------------------------------------------------------------

def _room() -> dict:
    if not ROOM.is_file():
        return {}
    try:
        return json.loads(ROOM.read_text())
    except ValueError:
        return {}


def room_claims() -> list[dict]:
    data = _room()
    if not data:
        return []
    messages = data.get("messages") or []
    texts = [m for m in messages if m.get("messageType") == "text"]
    by_seat: dict[str, int] = {}
    for m in texts:
        name = str(m.get("senderName") or "?")
        by_seat[name] = by_seat.get(name, 0) + 1
    seats = {m["senderId"] for m in messages
             if str(m.get("senderType", "")).lower() == "agent" and m.get("senderId")}

    tokens_in = tokens_out = 0
    for m in messages:
        hit = TOKEN_USAGE.match(str(m.get("content", "")))
        if hit:
            tokens_in += int(hit.group(1))
            tokens_out += int(hit.group(2))

    verdicts = {"ACCEPT": 0, "REJECT": 0}
    filler = 0
    for m in texts:
        head = " ".join(str(m.get("content", "")).split())
        hit = VERDICT.match(head)
        if hit:
            verdicts[hit.group(1)] += 1
        if FILLER.match(head):
            filler += 1

    architect = max(by_seat, key=lambda s: by_seat[s]) if by_seat else ""
    split = ", ".join(f"{v} from the {_role(k)}" for k, v in
                      sorted(by_seat.items(), key=lambda kv: -kv[1]))

    return [
        dict(id="room.total", source="room.json",
             states=f"the room holds {len(messages)} messages",
             near=r"\bmessages?\b", any=[r"\b%d\b" % len(messages)]),

        dict(id="room.scope", source="room.json",
             states=f'the download is a full session, not a filtered one '
                    f'(scope "{data.get("scope", "")}")',
             near=r"\broom\b|\bsession\b|\bdownload",
             any=[r"\*\*full session\*\*", r"\bfull session\b", r"scope[^\n]*\bfull\b"]),

        dict(id="room.seats", source="room.json",
             states=f"{len(seats)} distinct agent seats are in the room",
             near=r"\bseats?\b",
             any=[r"\b%d\s+(?:distinct\s+)?(?:agent\s+)?seats?\b" % len(seats),
                  r"[Tt]hree seats", r"\b3 seats\b"]),

        dict(id="room.text", source="room.json",
             states=f"{len(texts)} of those messages are the seats speaking",
             near=r"\bseat\b|\bagent", any=[
                 r"\b%d seat messages\b" % len(texts),
                 r"\b%d of them are the agents\b" % len(texts),
                 r"\b%d\b[^\n]*\bseats?\b" % len(texts)]),

        dict(id="room.byseat", source="room.json",
             states="the split across seats is " + split,
             near=r"\b(?:from the )?%s\b" % _role(architect),
             all=[r"\b%d (?:from the )?%s\b" % (v, _role(k))
                  for k, v in sorted(by_seat.items(), key=lambda kv: -kv[1])]),

        dict(id="room.accept", source="room.json",
             states=f"{verdicts['ACCEPT']} verdicts were ACCEPT",
             near=r"ACCEPT|verdict",
             any=[r"\b%d (?:acceptances|verdicts)\b" % verdicts["ACCEPT"],
                  r"\b%d ACCEPT\b" % verdicts["ACCEPT"],
                  r"[Ee]ight verdicts"] if verdicts["ACCEPT"] == 8 else
                 [r"\b%d (?:acceptances|verdicts)\b" % verdicts["ACCEPT"]]),

        dict(id="room.reject", source="room.json",
             states=f"{verdicts['REJECT']} verdicts were REJECT"
                    + (" -- every verdict was ACCEPT" if not verdicts["REJECT"] else ""),
             near=r"REJECT|verdict",
             any=[r"\b%d (?:rejections|REJECT)\b" % verdicts["REJECT"],
                  r"\b%d rejections?\b" % verdicts["REJECT"],
                  r"all (?:eight |\d+ )?ACCEPT"] if verdicts["REJECT"] == 0 else
                 [r"\b%d rejections?\b" % verdicts["REJECT"]]),

        dict(id="room.filler", source="room.json",
             states=f"{filler} of the seat messages is a filler message",
             near=r"filler|carries|pings|placeholder",
             any=[r"\b%d filler\b" % filler] if filler else
                  [r"not a single filler", r"every one of them carries",
                   r"no filler message", r"0 filler", r"carries a revision, a count"]),

        dict(id="room.tokens_in", source="room.json",
             states=f"{tokens_in:,} input tokens",
             near=r"token", any=[re.escape(f"{tokens_in:,}"), re.escape(str(tokens_in))]),

        dict(id="room.tokens_out", source="room.json",
             states=f"{tokens_out:,} output tokens",
             near=r"token", any=[re.escape(f"{tokens_out:,}"), re.escape(str(tokens_out))]),

        dict(id="room.floor", source="room.json",
             states="the token count is a floor, not a total, because the other two seats "
                    "report usage through their own adapters",
             near=r"floor|not a total",
             any=[r"floor[^\n]*not a total", r"not a total[^\n]*floor"]),

        dict(id="room.window", source="room.json",
             states="the room window runs 2026-10-02 to 2026-10-03, about 25 hours",
             near=r"2026-10", any=[r"2026-10-0[23]"]),

        dict(id="room.locks", source="room.json",
             states=f"{_locks_mentioned(data)} stage locks are announced in the room",
             near=r"lock", any=[rf"\b(?:{_locks_mentioned(data)}|{_word(_locks_mentioned(data))}) "
                                r"stage locks?\b"]),
    ]


def _summary() -> dict:
    found = sorted(RUNS.glob("*/summary.json")) if RUNS.is_dir() else []
    return (json.loads(found[-1].read_text()), found[-1].parent.name) if found else ({}, "")


def harness_claims() -> list[dict]:
    data, run_name = _summary()
    if not data:
        return []
    folders = data.get("folders") or {}
    claimed = sorted((n for n, f in folders.items() if f.get("claimed")), key=int)
    contiguous = max((int(n) for n in claimed), default=0)
    shares = {f.get("share") for f in folders.values() if f.get("share") is not None}

    return [
        dict(id="harness.folders", source=f"docs/harness-runs/{run_name}/summary.json",
             states=f"{len(folders)} stage folders were built and probed",
             rows=(STAGE_ROW, len(folders))),

        dict(id="harness.contiguous", source=f"docs/harness-runs/{run_name}/summary.json",
             states=f"highest contiguous stage is {contiguous}",
             near=r"contiguous",
             any=[re.escape(str(contiguous)), r"\b%d\b" % contiguous]),

        dict(id="harness.share", source=f"docs/harness-runs/{run_name}/summary.json",
             states="every folder scored share "
                     + "/".join(str(s) for s in sorted(shares)),
             near=r"share|1\.0",
             all=[re.escape(str(s)) for s in sorted(shares)]),

        dict(id="harness.mode", source=f"docs/harness-runs/{run_name}/summary.json",
             states="the run was in isolated mode, in a clean container",
             near=r"isolated|clean container", any=[r"isolated", r"clean container"]),

        dict(id="harness.claimed", source=f"docs/harness-runs/{run_name}/summary.json",
             states="every folder claimed its own stage",
             near=r"claim", any=[r"claims? (?:its|their) stage", r"claimed its stage",
                                 r"claims? stage \d"]),
    ]


def stale_claims() -> list[dict]:
    """Figures this repository has asserted before and has since corrected.

    The room did not change, so a token count or a stage count in a document can only be
    wrong because the document was not updated. Checking that the true figure is present
    does not catch a stale one sitting next to it -- which is exactly what happened: at
    one point `FACTORY.md` carried both 41 and 49 for the same message count, in
    consecutive paragraphs. So each of these is a figure that must appear nowhere.
    """
    data, run_name = _summary()
    folders = len((data.get("folders") or {})) if data else 4
    return [
        dict(id="stale.tokens_in", source="git history",
             states="the superseded token count 191,555 appears in no document",
             forbidden=[r"191,?555"]),
        dict(id="stale.tokens_out", source="git history",
             states="the superseded token count 16,068 appears in no document",
             forbidden=[r"16,?068"]),
        dict(id="stale.text_count", source="room.json",
             states="the superseded seat-message count 41 appears in no document",
             forbidden=[r"\b41 seat messages\b"]),
        dict(id="stale.stage_count", source=f"docs/harness-runs/{run_name}/summary.json",
             states=f"the superseded {folders - 1}-stage result appears in no document",
             forbidden=[rf"highest contiguous stage: {folders - 1}\b"]),
    ]


def git(*args: str) -> str:
    try:
        out = subprocess.run(["git", "-C", str(ROOT), *args],
                             capture_output=True, text=True, timeout=20)
    except (OSError, subprocess.SubprocessError):
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


def git_claims() -> list[dict]:
    if not git("rev-parse", "HEAD"):
        return []
    history = git("log", "--format=%H %s", "-80")
    present = [s for s in STAGE_LOCKS.values() if s in history]
    return [
        dict(id="git.locks", source="git log",
             states="every stage's locked revision is in the git history "
                    f"({len(present)}/{len(STAGE_LOCKS)})",
             all=[re.escape(sha) for sha in STAGE_LOCKS.values()]),
    ]


# --- checking ---------------------------------------------------------------

def all_claims() -> list[dict]:
    return room_claims() + harness_claims() + git_claims() + stale_claims()


def documents() -> list[tuple[pathlib.Path, str]]:
    out = []
    for name in DOCS:
        path = ROOT / name
        if path.is_file():
            out.append((path, path.read_text(errors="replace")))
    return out


def _hits(claim: dict, lines: list[str]) -> list[int]:
    """1-based line numbers in one document that carry this claim.

    `forbidden` inverts the test: every pattern has to appear nowhere.
    `rows` counts lines and is strict. `near` + `any`/`all` is per-line, which is how a
    figure that has to sit in a sentence gets checked. A bare `all` without `near` is
    document-scoped: every pattern has to appear somewhere, not all on one line, because
    the four stage revisions are four rows of one table.

    `forbidden` is not handled here -- see `_check_forbidden`, which has to look across
    every document at once.
    """
    if "rows" in claim:
        pattern, expected = claim["rows"]
        found = [n for n, line in enumerate(lines, 1) if re.match(pattern, line)]
        return found if len(found) == expected else []
    if not claim.get("near"):
        patterns = [p for p in claim.get("all") or [] if p]
        if not patterns:
            return []
        # Document-scoped: every pattern has to appear somewhere in the file, and the
        # lines reported are the ones carrying any of them, so the evidence table can
        # point at the rows rather than at line 1.
        hits = [n for n, line in enumerate(lines, 1)
                if any(re.search(p, line, re.I) for p in patterns)]
        return hits if all(re.search(p, "\n".join(lines), re.I) for p in patterns) else []
    hits = []
    for n, line in enumerate(lines, 1):
        if not re.search(claim["near"], line, re.I):
            continue
        if claim.get("all"):
            if all(re.search(p, line, re.I) for p in claim["all"] if p):
                hits.append(n)
        elif claim.get("any") and any(re.search(p, line, re.I) for p in claim["any"] if p):
            hits.append(n)
    return hits


def check() -> list[str]:
    docs = documents()
    if not docs:
        return [f"none of {', '.join(DOCS)} is present, so nothing can be checked"]
    problems = []
    for claim in all_claims():
        if claim.get("forbidden"):
            problems += _check_forbidden(claim, docs)
            continue
        if not any(_hits(claim, text.splitlines()) for _, text in docs):
            where = ""
            if "rows" in claim:
                pattern, expected = claim["rows"]
                for path, text in docs:
                    rows = [re.match(pattern, l) for l in text.splitlines()]
                    if any(rows):
                        where = (f" -- {path.name} has "
                                 f"{sum(1 for r in rows if r)} such row(s), "
                                 f"evidence says {expected}")
            problems.append(f"{claim['id']}: no line in "
                            f"{' or '.join(p.name for p, _ in docs)} states that "
                            f"{claim['states']} [{claim['source']}]{where}")
    return problems


def _check_forbidden(claim: dict, docs: list[tuple[pathlib.Path, str]]) -> list[str]:
    """A retired figure has to appear in no document at all.

    Checked across every document rather than per document: the failure being guarded
    against is one document still carrying a number another document has already
    corrected, and testing each file on its own would let the correct one hide the wrong
    one.
    """
    found = []
    for path, text in docs:
        for n, line in enumerate(text.splitlines(), 1):
            for pattern in claim["forbidden"]:
                if re.search(pattern, line, re.I):
                    found.append(f"{claim['id']}: {path.name}:{n} still says {pattern!r}; "
                                 f"{claim['states']} [{claim['source']}]")
    return found


def markdown() -> str:
    claims = all_claims()
    out = [
        "# Evidence — every figure in these documents, and where it comes from",
        "",
        "Generated by `python3 verify_claims.py --markdown`, checked by",
        "`python3 verify_claims.py` in CI. Do not edit this file by hand: edit the claim",
        "list in `verify_claims.py`, which is the machine-readable half.",
        "",
        "Three things have to agree, and the rule is that the evidence wins. When a",
        "number below disagrees with a document, the document is wrong.",
        "",
        "| Claim | What the evidence says | Source | In the documents |",
        "|---|---|---|---|",
    ]
    docs = documents()
    for claim in claims:
        if claim.get("forbidden"):
            places = [f"`{p.name}:{n}`"
                      for p, t in docs
                      for n, line in enumerate(t.splitlines(), 1)
                      if any(re.search(x, line) for x in claim["forbidden"])]
            out.append(f"| `{claim['id']}` | {claim['states']} | `{claim['source']}` | "
                       + (", ".join(places) + " **still present**" if places else "clear")
                       + " |")
            continue
        where = []
        for path, text in docs:
            hits = _hits(claim, text.splitlines())
            if hits:
                where.append(f"`{path.name}:{hits[0]}`")
        out.append(f"| `{claim['id']}` | {claim['states']} | `{claim['source']}` | "
                   f"{', '.join(where) or '**missing**'} |")
    out += ["",
            f"{len(claims)} claim(s). Sources: `room.json` (the seat log as downloaded),",
            "`docs/harness-runs/*/summary.json` (the event's own harness), and `git log`.",
            ""]
    return "\n".join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--list", action="store_true",
                        help="print every claim and the evidence, check nothing")
    parser.add_argument("--markdown", metavar="PATH",
                        help="write the evidence table as markdown and exit")
    args = parser.parse_args(argv)

    claims = all_claims()
    if not claims:
        print("no evidence: room.json and docs/harness-runs are both missing or unreadable",
              file=sys.stderr)
        return 2

    if args.markdown:
        pathlib.Path(args.markdown).write_text(markdown())
        print(f"wrote {args.markdown} ({len(claims)} claims)", file=sys.stderr)
        return 0

    if args.list:
        width = max(len(c["id"]) for c in claims)
        for claim in claims:
            print(f"{claim['id']:<{width}}  {claim['states']}")
        print(f"\n{len(claims)} claim(s) from room.json, docs/harness-runs and git.")
        return 0

    problems = check()
    for problem in problems:
        print(problem, file=sys.stderr)
    print(f"{len(problems)} drift(s) against {len(claims)} claim(s)" if problems else
          f"ok -- all {len(claims)} claims in {', '.join(p.name for p, _ in documents())} "
          f"match room.json, docs/harness-runs and git", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())